# Generated by Django 4.1.3 on 2023-03-22 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Project',
            new_name='Prospect',
        ),
    ]
